FROM microsoft/dotnet:2.1-sdk-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY demoapp/*.csproj ./demoapp/
RUN dotnet restore

# copy everything else and build app
COPY demoapp/. ./demoapp/
WORKDIR /app/demoapp
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine AS runtime
WORKDIR /app
COPY --from=build /app/demoapp/out ./
ENTRYPOINT ["dotnet", "demoapp.dll"]